# whitelist
branches:
  only:
    - master
sudo: required
services:
  - docker
language: ruby
rvm:
  - 2.3.1
before_install:
  #Set up Docker exports
  - export AUTHOR=`git --no-pager show -s --format='%an <%ae>'`
  - export DATE=`TZ=America/New_York date "+%m-%d-%y-%H%M"`
  - export DOCKER_IMAGE="matchbox/nci-treatment-arm-processor-api"
  - echo "TravisBuild=$TRAVIS_BUILD_NUMBER" > build_number.html &&
        echo "Commit=$TRAVIS_COMMIT" >> build_number.html       &&
        echo "TravisJob=$TRAVIS_JOB_ID" >> build_number.html    &&
        echo "Author=$AUTHOR" >> build_number.html              &&
        echo "BuildTime=$DATE" >> build_number.html             &&
        echo "Docker=$DOCKER_IMAGE:$DATE" >> build_number.html
  - cat ./build_number.html
script:
  - RAILS_ENV=test bundle exec rspec spec/
    #Build Docker image
  - docker build -t $DOCKER_IMAGE:$DATE -t $DOCKER_IMAGE:latest .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  # - docker run -it --rm -e "RAILS_ENV=test" $DOCKER_IMAGE:$DATE 
  #     bundle exec rspec spec/
after_success:
  - bundle exec codeclimate-test-reporter
  - docker images
  - docker push $DOCKER_IMAGE # Pushes both date and latest
  #Deploy to AWS IntTest
  - docker run -it --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY 
    -e AWS_DEFAULT_REGION=us-east-1 silintl/ecs-deploy 
    --cluster PedMatch-IntTest-Backend --service-name PedMatch-nci-treatment-arm-processor-api-INTTEST 
    -i $DOCKER_IMAGE:$DATE
  #Trigger Travis bdd tests
  - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json" -H "Travis-API-Version:3" -H "Authorization:token $TRAVIS_TOKEN" -d "{\"request\":{\"message\":\"Triggered by nci-treatment-arm-processor-api $TRAVIS_COMMIT\", \"branch\":\"master\", \"config\":{\"env\":{\"matrix\":[\"TRIGGER_REPO=nci-treatment-arm-processor-api;TRIGGER_VER=$DATE;CUC_TAG=@treatment_arm\"]}}}}" https://api.travis-ci.org/repo/CBIIT%2Fnci-uMatch-bddtests/requests
notifications:
  slack: clinicalbiomed:gRp5LqKElNOjUUMPLlq4qC1j
addons:
  code_climate:
        repo_token: 55a2dc7851ea13b067e7d2ef6d86e1068da4634edc063a013b9af2a48c6d791a
