development:
  aws_dynamo_endpoint: "http://localhost:8000"
  aws_region: "us-east-1"
  queue_name: "treatment_arm_development"
  shoryuken_delay: "5"
  shoryuken_concurrency: "10"
  table_prefix: "ta"
  PORT: "10236"
  cog_url: "http://localhost:3000"
  cog_treatment_arms: "/treatmentArms"
  read_capacity_units: "30"
  write_capacity_units: "30"

test:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"
  queue_name: "treatment_arm_test"
  shoryuken_delay: "5"
  shoryuken_concurrency: "10"
  table_prefix: "ta"
  PORT: "10236"
  cog_url: "http://pedmatch.org:3000"
  cog_treatment_arms: "/treatmentArms"
  read_capacity_units: "30"
  write_capacity_units: "30"

uat:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"
  queue_name: "treatment_arm"
  shoryuken_delay: "5"
  shoryuken_concurrency: "10"
  table_prefix: "ta"
  PORT: "10236"
  cog_url: "http://uat.pedmatch.org:3000"
  cog_treatment_arms: "/treatmentArms"
  read_capacity_units: "30"
  write_capacity_units: "30"

production:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"
  queue_name: "treatment_arm"
  shoryuken_delay: "5"
  shoryuken_concurrency: "10"
  table_prefix: "ta"
  PORT: "10236"
  cog_url: " "
  cog_treatment_arms: "/treatmentArms"
  read_capacity_units: "30"
  write_capacity_units: "30"
