development:
  aws_dynamo_endpoint: "http://localhost:8000"
  aws_region: "us-east-1"
  queue_name: "treatment_arm_development"
  shoryuken_delay: "5"
  shoryuken_concurrency: "10"
  table_prefix: "ta"
  PORT: "10236"

test:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"
  queue_name: "treatment_arm_test"
  shoryuken_delay: "5"
  shoryuken_concurrency: "10"
  table_prefix: "ta"
  PORT: "10236"

uat:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"
  queue_name: "treatment_arm"
  shoryuken_delay: "5"
  shoryuken_concurrency: "10"
  table_prefix: "ta"
  PORT: "10236"

production:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"
  queue_name: "treatment_arm"
  shoryuken_delay: "5"
  shoryuken_concurrency: "10"
  table_prefix: "ta"
  PORT: "10236"
