development:
  aws_dynamo_endpoint: "http://localhost:8000"
  aws_region: "us-east-1"
  queue_name: <%= ENV["TA_QUEUE_NAME"] %>
  shoryuken_delay: "5"
  shoryuken_concurrency: "10"
  table_prefix: "ta"
  PORT: "10236"
  cog_url: "http://localhost:3000"
  cog_treatment_arms: "/treatmentArms"
  patient_api_url: "http://localhost:3010"
  patient_assignment: "/treatmentArmsUpdated"
  read_capacity_units: "30"
  write_capacity_units: "30"

test:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"
  queue_name: "treatment_arm_queue"
  shoryuken_delay: "5"
  shoryuken_concurrency: "10"
  table_prefix: "ta"
  PORT: "10236"
  cog_url: "http://pedmatch-int.nci.nih.gov:3000"
  cog_treatment_arms: "/treatmentArms"
  patient_api_url: "https://pedmatch-int.nci.nih.gov:3010"
  patient_assignment: "/treatmentArmsUpdated"
  read_capacity_units: "30"
  write_capacity_units: "30"

uat:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"
  queue_name: "treatment_arm_queue"
  shoryuken_delay: "5"
  shoryuken_concurrency: "10"
  table_prefix: "ta"
  PORT: "10236"
  cog_url: " "
  cog_treatment_arms: "/treatmentArms"
  patient_api_url: "https://pedmatch-uat.nci.nih.gov:3010"
  patient_assignment: "/treatmentArmsUpdated"
  read_capacity_units: "30"
  write_capacity_units: "30"

production:
  aws_dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  aws_region: "us-east-1"
  queue_name: "treatment_arm_queue"
  shoryuken_delay: "5"
  shoryuken_concurrency: "10"
  table_prefix: "ta"
  PORT: "10236"
  cog_url: " "
  cog_treatment_arms: "/treatmentArms"
  patient_api_url: "https://pedmatch.nci.nih.gov:3010"
  patient_assignment: "/treatmentArmsUpdated"
  read_capacity_units: "30"
  write_capacity_units: "30"
