# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &defaults
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

development:
  <<: *defaults
  secret_key_base: 30d03dc8d30bd095bef9f718db56c972bbbd86964ba539a9573d998d6445a4d066a2eec1146d2231fec10f84bcc0104f258cfb74375ada25fce86b245e27587b

test:
  <<: *defaults
  secret_key_base: b8f730a863c27646c73ebb700ef2fb513dcab3f58b24a3495f3d96f9127d5534b2df54a32dd0a75b8b6cb2ddb5a561bb08b3d54d9ab0d794f0eadb00e504d8d4

uat:
  <<: *defaults
  secret_key_base: b8f730a863c27646c73ebb700ef2fb513dcab3f58b24a3495f3d96f9127d5534b2df54a32dd0a75b8b6cb2ddb5a561bb08b3d54d9ab0d794f0eadb00e504d8d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: b8f730a863c27646c73ebb700ef2fb513dcab3f58b24a3495f3d96f9127d5534b2df54a32dd0a75b8b6cb2ddb5a561bb08b3d54d9ab0d794f0eadb00e504d8d4
